version: '4'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - backend
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=production
